#pragma once

#ifndef VOXCORTEX_FIRMWARE_VERSION
#define VOXCORTEX_FIRMWARE_VERSION "dev"
#endif

#ifndef VOXCORTEX_FIRMWARE_BUILD
#define VOXCORTEX_FIRMWARE_BUILD "local"
#endif

#ifndef VOXCORTEX_FIRMWARE_BOARD
#define VOXCORTEX_FIRMWARE_BOARD "m5stick-c-plus2"
#endif

#ifndef VOXCORTEX_PROTOCOL_VERSION
#define VOXCORTEX_PROTOCOL_VERSION 1
#endif
